expose:
  type: ingress
  ingress:
    hosts:
      core: harbor.k8s.labs.itmo.loc
    className: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      enabled: true
      secretName: k8s-tls
externalURL: https://harbor.k8s.labs.itmo.loc
harborAdminPassword: "admin"
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: microk8s-hostpath
      accessMode: ReadWriteOnce
      size: 5Gi