expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: k8s-tls
  ingress:
    hosts:
      core: harbor.k8s.labs.itmo.loc
    className: nginx
externalURL: https://harbor.k8s.labs.itmo.loc
harborAdminPassword: "admin"
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: microk8s-hostpath
      accessMode: ReadWriteOnce
      size: 5Gi